services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      # TODO: add services later
  # user-service:
  #   build: ./services/user-service
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     DATABASE_URL: postgresql://dbadmin:localpassword@postgres:5432/ecommerce

volumes:
  postgres_data:
