apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Prometheus
  - prometheus/rbac.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  
  # Loki
  - loki/configmap.yaml
  - loki/deployment.yaml
  - loki/service.yaml
  
  # Promtail
  - promtail/rbac.yaml
  - promtail/configmap.yaml
  - promtail/deployment.yaml
  
  # Grafana
  - grafana/secret.yaml
  - grafana/datasources.yaml
  - grafana/dashboards-provisioning.yaml
  - grafana/dashboard-definitions.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml

