apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: default
data:
  USER_SERVICE_URL: "http://user-service.default.svc.cluster.local:8083"
  ORDER_SERVICE_URL: "http://order-service.default.svc.cluster.local:8082"
  SEARCH_SERVICE_URL: "http://search-service.default.svc.cluster.local:8081"
